### ISSUE TITLE
draft-ietf-dnsop-zoneversion

### ISSUE THREAD

**Issue by moonshiner** [wkumari/Temp-DNSOP_Doc_Tracker#12]
## Link: 

https://datatracker.ietf.org/doc/draft-ietf-dnsop-zoneversion/

## Authors:
*  H. Salgado
* M. Vergara
* D Wessels

## Related drafts

We need a Followup WGLC

**Comment by wkumari** [comment]
Second, short WGLC started: https://mailarchive.ietf.org/arch/msg/dnsop/kpKU7P5Gxsmw-3qPJmMix-TdzO4/

**Comment by moonshiner** [comment]
Updated the shepherds write up and re-submitted.

**Comment by wkumari** [comment]
You say:
"Working Group Summary:
WG worked and collaborated on resolving any and all issues. No rough consensus."

This is ambiguous — "No rough consensus" could be understood to mean that there is no consensus, rough or otherwise. Yes, it should be clear what was intended, but I'm *sure* that some set of ADs will question this, so…


Please also add names for the document shepherd and responsible AD...

**Comment by moonshiner** [comment]
I fixed this up with apologies.  I went through it another time looking for issues.

**Comment by wkumari** [comment]
Ta, and no worries!

**Comment by wkumari** [comment]
IETF LC started

**Comment by moonshiner** [comment]
Revised ID needed.

**Comment by wkumari** [comment]
RFC Editor state: EDIT

**Comment by moonshiner** [comment]
RFC 9660 - AUTH48
